version: "3.9"
services:
  angular-build:
    build:
      context: .
      dockerfile: Dockerfile
    image: sportbuddiesappfe-builder:latest # Etiqueta la imagen del builder

  angular: # Servicio para servir la aplicación (usa la imagen de Nginx)
    image: nginx:alpine
    container_name: sport-buddies-fe
    ports:
      - "81:80"
      # - "443:443" # Descomenta si usas HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - sportbuddiesappfe-dist:/usr/share/nginx/html # Volumen con los archivos estáticos
    depends_on:
      - angular-build # Dependencia para que se construya antes de iniciar Nginx
    networks:
      - sportbuddiesfe-network

networks:
  sportbuddiesfe-network:

volumes:
  sportbuddiesappfe-dist: