version: "3.9"
services:
  angular-build:
    build:
      context: .
      dockerfile: Dockerfile
    image: sportbuddiesappfe-builder:latest
    volumes:
      - angular-build-volume:/app/dist # <-- Agrega esta línea

  angular:
    image: nginx:alpine
    container_name: SportBuddiesApp-fe-Angular
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - sportbuddiesappfe-dist:/usr/share/nginx/html
    depends_on:
      - angular-build
      - copy-dist
    networks:
      - sportbuddiesfe-network

  copy-dist:
    image: alpine/git
    volumes:
      - angular-build-volume:/app/dist 
      - sportbuddiesappfe-dist:/usr/share/nginx/html
    depends_on:
      - angular-build
    command: /bin/sh -c "apk add --no-cache bash && cp -r /app/dist/* /usr/share/nginx/html && while true; do sleep 30; done"

networks:
  sportbuddiesfe-network:

volumes:
  sportbuddiesappfe-dist:
  angular-build-volume: # <-- Define el volumen aquí