services:
  angular:
    build:
      context: ./
      dockerfile: ./Dockerfile.angular # Crea un Dockerfile específico para Angular
    # No expongas el puerto 4200, Nginx se encargará de la comunicación
    # ports:
    #   - "4200:80"  <- Elimina esta línea
    networks:
      - sportbuddies-fe-network

  nginx:
    image: nginx:alpine
    container_name: sport-buddies-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist/sport-buddies-app-fe:/usr/share/nginx/html # Monta el directorio dist
    depends_on:
      - angular
    networks:
      - sportbuddies-fe-network

networks:
  mi-red: