services:
  angular:
    build:
      context: ./
      dockerfile: ./Dockerfile
      ports:
        - "4200:80"
    networks:
      - sportbuddiesfe-network

  nginx:
    image: nginx:alpine
    container_name: sport-buddies-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist/sport-buddies-app-fe:/usr/share/nginx/html # Monta el directorio dist
    depends_on:
      - angular
    networks:
      - sportbuddiesfe-network

networks:
  sportbuddiesfe-network: