version: "3.9"
services:
  angular-build:
    # ... (configuración del builder)

  angular:
    image: nginx:alpine
    container_name: sport-buddies-fe
    ports:
      - "81:80" # Puerto 81 en el host, 80 en el contenedor
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - sportbuddiesappfe-dist:/usr/share/nginx/html
    depends_on:
      - angular-build
      - copy-dist # Nueva dependencia
    networks:
      - sportbuddiesfe-network

  copy-dist: # Nuevo servicio para copiar los archivos al volumen
    image: alpine/git # Imagen con git para clonar el repo si es necesario
    volumes:
      - sportbuddiesappfe-dist:/usr/share/nginx/html
    depends_on:
      - angular-build
    command: /bin/sh -c "apk add --no-cache bash && cp -r /app/dist/* /usr/share/nginx/html && while true; do sleep 30; done"


networks:
  sportbuddiesfe-network:

volumes:
  sportbuddiesappfe-dist: